### ISSUE TITLE
Trumbowyg component huge buttons

### ISSUE THREAD

**Issue by VictorPacheco** [Apress/practical-oracle-jet#1]
I follow the book, but in chapter 8 Trumbowyg doesn't work as expected:

![issue](https://user-images.githubusercontent.com/13750775/59651482-9cc34e80-914f-11e9-899e-9205246a1d02.png)

**Comment by danneh150** [comment]
Hi Victor!

Would it be possible for you to share your source code so I can take a deeper look?

Thanks!
Dan

**Comment by danneh150** [comment]
Hey @VictorPacheco,

I've managed to replicate the issue you are seeing. Could you check and make sure that the CSS file has been imported into the theme as below:

![image](https://user-images.githubusercontent.com/8373754/59751154-f2931600-9277-11e9-9d95-21afea814533.png)

Let me know how you get on.

**Comment by VictorPacheco** [comment]
Hi, i struggled a little, then simply edit mosTheme.scss and save, the ide (WebStorm) recompile and works. Thank you.
![solucion](https://user-images.githubusercontent.com/13750775/59965038-bf968f80-94ce-11e9-8fdf-973782da1d49.png)
